#!/usr/bin/env node
/**
 * Flags generator — writes frontend/src/config/flags-runtime.js.
 *
 * This file is GENERATED and git-ignored (Amplify likewise rewrites it inline
 * at deploy time), so toggling DEV mode for local design work never shows up as
 * a diff and can never accidentally ship DEV:true to production.
 *
 * Usage:  node scripts/gen-flags.mjs [dev|local|prod]
 *   dev    DEV mock mode — no backend, mock data, auto-admin, INSPO on.
 *          The fast path for iterating on designs.  (npm run dev)
 *   local  DEV off, talks to a backend at API_URL (default localhost:3000).
 *   prod   DEV off, API_URL from the API_URL env var (local prod-like builds).
 *
 * Env overrides (any mode): API_URL, DEV_DELAY, MOCK_USER, MOCK_TOKEN.
 */
import { writeFileSync, mkdirSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const mode = (process.argv[2] || 'dev').toLowerCase();
const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outPath = join(root, 'frontend', 'src', 'config', 'flags-runtime.js');

const PRESETS = {
  dev:   { DEV: true,  API_URL: 'http://localhost:3000', MOCK_USER: 'designer@dev.local', MOCK_TOKEN: 'dev-token', DEV_DELAY: 0, INSPO: true },
  local: { DEV: false, API_URL: 'http://localhost:3000', MOCK_USER: '',                   MOCK_TOKEN: '',          DEV_DELAY: 0, INSPO: true },
  prod:  { DEV: false, API_URL: process.env.API_URL || '', MOCK_USER: '',                 MOCK_TOKEN: '',          DEV_DELAY: 0, INSPO: true },
};

const cfg = PRESETS[mode];
if (!cfg) {
  console.error(`✗ Unknown flags mode "${mode}". Use: dev | local | prod`);
  process.exit(1);
}

// Environment overrides win over the preset.
if (process.env.API_URL)    cfg.API_URL = process.env.API_URL;
if (process.env.DEV_DELAY)  cfg.DEV_DELAY = Number(process.env.DEV_DELAY) || 0;
if (process.env.MOCK_USER)  cfg.MOCK_USER = process.env.MOCK_USER;
if (process.env.MOCK_TOKEN) cfg.MOCK_TOKEN = process.env.MOCK_TOKEN;

const content = `// AUTO-GENERATED by scripts/gen-flags.mjs (mode: ${mode}). Do not edit by hand.
// Regenerate:  npm run flags:${mode}   ·   mock dev loop:  npm run dev
export const CONFIG = {
  DEV:        ${cfg.DEV},
  API_URL:    '${cfg.API_URL}',
  MOCK_USER:  '${cfg.MOCK_USER}',
  MOCK_TOKEN: '${cfg.MOCK_TOKEN}',
  DEV_DELAY:  ${cfg.DEV_DELAY},
  // Dev flag for the inspiration board. The INSPO tab shows when DEV && INSPO
  // (mock data, no backend), or via the per-admin \`inspo\` trait once the
  // backend commands (30–36) are wired.
  INSPO:      ${cfg.INSPO},
};

export function devLog(...args) {
  if (CONFIG.DEV) console.log('[DEV]', ...args);
}
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, content, 'utf8');
console.log(`🚩 flags-runtime.js → mode "${mode}"  (DEV=${cfg.DEV}, API_URL=${cfg.API_URL || '∅'}, INSPO=${cfg.INSPO})`);
